SQL> SELECT customer.customer_id, customer.customer_name, painting.painting_name, transaction.transaction_date
  2  FROM customer, painting, leased_painting, transaction
  3  WHERE customer.customer_id = leased_painting.customer_id
  4  AND painting.painting_id = leased_painting.painting_id
  5  AND transaction.transaction_id = leased_painting.transaction_id
  6  AND customer.customer_id = 'C002';

CUSTOME CUSTOMER_NAME                  PAINTING_NAME                  TRANSACTI                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
------- ------------------------------ ------------------------------ ---------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
C002    Asa Howard                     Isaiah                         12-AUG-21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
C002    Asa Howard                     Landscape Near Figueras        12-AUG-21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
C002    Asa Howard                     Graden Path at Giverny         12-AUG-21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

SQL> SPOOL OFF
