SQL> SELECT *
  2  FROM painting
  3  WHERE (SYSDATE - last_leased_date) >= 90
  4  AND (SYSDATE - last_leased_date) <= 120;

PAINTIN PAINTING_NAME                  THEME                          ARTIST_ SUBMITTED LAST_LEAS RENTAL_PRICE AVAILABLE_STATUS     OWNER_I                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
------- ------------------------------ ------------------------------ ------- --------- --------- ------------ -------------------- -------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
P001    Mountain Retreat               Landscape                      A001    12-JAN-21 10-SEP-21        50000 Available            O002                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
P007    Cat Catching a Bird            Animal                         A002    13-FEB-21 24-SEP-21        45000 Available            O003                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

SQL> SPOOL OFF
