SQL> SELECT *
  2  FROM customer
  3  WHERE customer_id =
  4  			(SELECT leased_painting.customer_id
  5  			FROM leased_painting
  6  			GROUP BY leased_painting.customer_id
  7  			HAVING count(*) > 4 );

CUSTOME CUSTOMER_NAME                  CUSTOMER_CONTACT_NUMBER CUSTOMER_TYPE   CUSTOMER_CATEGO                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
------- ------------------------------ ----------------------- --------------- ---------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
C003    Bleachers                                   9843111145 Company         VIP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

SQL> SPOOL OFF
