SQL> SELECT painting_id, painting_name, CAST((((last_leased_date - submitted_date)/30) * rental_price) AS INT) AS "COLLECTED RENTAL AMOUNT"
  2  FROM painting
  3  WHERE ROWNUM <=5
  4  ORDER BY "COLLECTED RENTAL AMOUNT" DESC;

PAINTIN PAINTING_NAME                  COLLECTED RENTAL AMOUNT                                                                                                                                                                                                                                                                                                                                                                                                                                                      
------- ------------------------------ -----------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                      
P003    Starry Night                                    608000                                                                                                                                                                                                                                                                                                                                                                                                                                                      
P001    Mountain Retreat                                401667                                                                                                                                                                                                                                                                                                                                                                                                                                                      
P002    Alaskan Waterfall                               362667                                                                                                                                                                                                                                                                                                                                                                                                                                                      
P004    Mona Lisa                                       302500                                                                                                                                                                                                                                                                                                                                                                                                                                                      
P005    The Sunflowers                                  269500                                                                                                                                                                                                                                                                                                                                                                                                                                                      

SQL> SPOOL OFF
