SQL> SELECT painting.artist_id, artist.artist_name, SUM(rental_price) AS "PAINTINGS SOLD VALUE"
  2  FROM painting, artist
  3  WHERE painting.artist_id = artist.artist_id
  4  AND ((SYSDATE - last_leased_date) < 30)
  5  GROUP BY painting.artist_id, artist.artist_name;

ARTIST_ ARTIST_NAME                    PAINTINGS SOLD VALUE                                                                                                                                                                                                                                                                                                                                                                                                                                                         
------- ------------------------------ --------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                         
A004    Vincent Van Gogh                              65000                                                                                                                                                                                                                                                                                                                                                                                                                                                         
A008    Salvador Dali                                 60000                                                                                                                                                                                                                                                                                                                                                                                                                                                         
A001    Bob Ross                                      40000                                                                                                                                                                                                                                                                                                                                                                                                                                                         

SQL> SPOOL OFF
